import { CITIES } from "@/domain/cities";
import { BudgetTier, City } from "@/domain/types";
import { generateTripPlan } from "@/features/planner/engine";
import { TripIntent } from "@/features/planner/types";

/**
 * Budget-first discovery: instead of picking a city and being told the price,
 * name the money and be told where it reaches.
 *
 * The estimate is not a separate cost model — it is a real plan, generated by
 * the same engine the planner uses, for the same trip. So the figure shown
 * here is the figure the traveler sees after clicking through, travel days,
 * flights home and all.
 */

/** Best experience first — a trip that fits at luxury beats one that doesn't. */
const TIERS: BudgetTier[] = ["luxury", "comfort", "backpacker"];

const TIER_RANK: Record<BudgetTier, number> = {
  luxury: 3,
  comfort: 2,
  backpacker: 1,
};

export type AffordabilityQuery = {
  originCityId: string;
  /** All-in spend per person, in €. */
  budget: number;
  nights: number;
  companions: TripIntent["companions"];
  /** 0-11; sharpens the estimate's weather notes but not its price. */
  travelMonth?: number;
};

export type AffordableTrip = {
  city: City;
  /** The most comfortable tier this budget covers, or the cheapest if none. */
  tier: BudgetTier;
  /** All-in per person, from a real generated plan. */
  total: number;
  /** Left over at that tier — negative when the trip doesn't fit. */
  headroom: number;
};

export type AffordabilityResult = {
  /** Trips the budget covers, best-value first. */
  affordable: AffordableTrip[];
  /** The closest few that don't fit, cheapest first. */
  nearMisses: AffordableTrip[];
};

function intentFor(
  query: AffordabilityQuery,
  city: City,
  tier: BudgetTier,
): TripIntent {
  return {
    mode: "custom",
    originCityId: query.originCityId,
    selectedCityIds: [city.id],
    duration: query.nights,
    travelMonth: query.travelMonth,
    companions: query.companions,
    interests: [],
    region: "any",
    vibe: { pace: "balanced", budget: tier, climate: "any" },
  };
}

/** The best tier this budget covers for one city, or the cheapest attempt. */
function priceCity(
  query: AffordabilityQuery,
  city: City,
  cities: City[],
): AffordableTrip {
  let cheapest: AffordableTrip | null = null;

  for (const tier of TIERS) {
    const total = generateTripPlan(intentFor(query, city, tier), cities).budget.total;
    const trip = { city, tier, total, headroom: query.budget - total };

    if (total <= query.budget) return trip;
    cheapest = trip; // TIERS runs priciest → cheapest, so this keeps improving.
  }

  // Unreachable in practice: the loop always runs at least once.
  return cheapest ?? { city, tier: "backpacker", total: 0, headroom: query.budget };
}

/**
 * Where this budget reaches. Affordable trips are ranked by the experience
 * they buy — the best tier that fits, then the most trip for the money —
 * because the question is "what can I get", not "what is cheapest".
 */
export function affordableTrips(
  query: AffordabilityQuery,
  cities: City[] = CITIES,
): AffordabilityResult {
  const priced = cities
    .filter((city) => city.id !== query.originCityId)
    .map((city) => priceCity(query, city, cities));

  const affordable = priced
    .filter((trip) => trip.headroom >= 0)
    .sort(
      (a, b) =>
        TIER_RANK[b.tier] - TIER_RANK[a.tier] ||
        b.total - a.total ||
        a.city.id.localeCompare(b.city.id),
    );

  const nearMisses = priced
    .filter((trip) => trip.headroom < 0)
    .sort((a, b) => a.total - b.total || a.city.id.localeCompare(b.city.id))
    .slice(0, 3);

  return { affordable, nearMisses };
}

/** The planner link that reproduces one of these trips in full. */
export function plannerUrlFor(
  trip: AffordableTrip,
  query: AffordabilityQuery,
): string {
  const params = new URLSearchParams({
    destination: trip.city.id,
    origin: query.originCityId,
    travelers: query.companions,
    budget: trip.tier,
  });
  if (query.travelMonth != null) params.set("month", String(query.travelMonth));
  return `/planner?${params.toString()}`;
}
