import { City } from "../types";

export const BALKANS: City[] = [
  {
    id: "athens-gr",
    name: "Athens",
    country: "Greece",
    region: "balkans",
    coords: { lat: 37.9838, lng: 23.7275 },
    climate: "warm",
    interests: ["history", "culture", "food"],
    stayPerNight: { backpacker: 25, comfort: 85, luxury: 220 },
    foodPerDay: { backpacker: 20, comfort: 45, luxury: 100 },
    minDays: 2,
    maxDays: 5,
    pois: [
      {
        id: "athens-gr-acropolis",
        name: "Acropolis",
        category: "sight",
        coords: { lat: 37.9715, lng: 23.7257 },
        price: 20,
        description: "Ancient citadel crowned by the Parthenon.",
      },
      {
        id: "athens-gr-acropolis-museum",
        name: "Acropolis Museum",
        category: "museum",
        coords: { lat: 37.9684, lng: 23.7287 },
        price: 15,
        description: "Modern museum housing artifacts from the Acropolis.",
      },
      {
        id: "athens-gr-plaka",
        name: "Plaka",
        category: "sight",
        coords: { lat: 37.973, lng: 23.728 },
        price: 0,
        description: "Charming old neighborhood beneath the Acropolis.",
      },
      {
        id: "athens-gr-ancient-agora",
        name: "Ancient Agora",
        category: "sight",
        coords: { lat: 37.9755, lng: 23.7224 },
        price: 10,
        description: "Ruins of the ancient marketplace and civic center.",
      },
      {
        id: "athens-gr-plaka-taverna",
        name: "Plaka Taverna",
        category: "food",
        coords: { lat: 37.9719, lng: 23.729 },
        price: 30,
        description: "Traditional taverna serving classic Greek dishes.",
      },
      {
        id: "athens-gr-monastiraki-market",
        name: "Monastiraki Market",
        category: "sight",
        coords: { lat: 37.9765, lng: 23.7256 },
        price: 0,
        description: "Bustling flea market square full of shops and stalls.",
      },
      {
        id: "athens-gr-rooftop-bars",
        name: "Rooftop Bars",
        category: "nightlife",
        coords: { lat: 37.975, lng: 23.73 },
        price: 25,
        description: "Rooftop bars with sweeping views over the Acropolis.",
      },
    ],
  },
  {
    id: "dubrovnik-hr",
    name: "Dubrovnik",
    country: "Croatia",
    region: "balkans",
    coords: { lat: 42.6507, lng: 18.0944 },
    climate: "warm",
    interests: ["history", "beach", "culture"],
    stayPerNight: { backpacker: 35, comfort: 110, luxury: 280 },
    foodPerDay: { backpacker: 25, comfort: 55, luxury: 120 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "dubrovnik-hr-old-town-walls",
        name: "Old Town Walls",
        category: "sight",
        coords: { lat: 42.6414, lng: 18.1101 },
        price: 35,
        description: "Walk the medieval walls encircling the Old Town.",
      },
      {
        id: "dubrovnik-hr-stradun",
        name: "Stradun",
        category: "sight",
        coords: { lat: 42.6408, lng: 18.1097 },
        price: 0,
        description: "Main limestone-paved street through the Old Town.",
      },
      {
        id: "dubrovnik-hr-lokrum-island",
        name: "Lokrum Island",
        category: "nature",
        coords: { lat: 42.6272, lng: 18.1194 },
        price: 27,
        description: "Nearby island retreat with botanical gardens.",
      },
      {
        id: "dubrovnik-hr-banje-beach",
        name: "Banje Beach",
        category: "nature",
        coords: { lat: 42.6407, lng: 18.1177 },
        price: 0,
        description: "Popular pebble beach with views of the Old Town.",
      },
      {
        id: "dubrovnik-hr-cable-car",
        name: "Dubrovnik Cable Car",
        category: "activity",
        coords: { lat: 42.6444, lng: 18.1131 },
        price: 27,
        description: "Cable car up Mount Srđ for sweeping panoramas.",
      },
      {
        id: "dubrovnik-hr-fish-restaurant",
        name: "Old Town Seafood Restaurant",
        category: "food",
        coords: { lat: 42.642, lng: 18.1088 },
        price: 45,
        description: "Fresh seafood restaurant tucked in the Old Town.",
      },
    ],
  },
  {
    id: "split-hr",
    name: "Split",
    country: "Croatia",
    region: "balkans",
    coords: { lat: 43.5081, lng: 16.4402 },
    climate: "warm",
    interests: ["history", "beach", "culture"],
    stayPerNight: { backpacker: 28, comfort: 85, luxury: 200 },
    foodPerDay: { backpacker: 20, comfort: 45, luxury: 100 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "split-hr-diocletians-palace",
        name: "Diocletian's Palace",
        category: "sight",
        coords: { lat: 43.5081, lng: 16.4402 },
        price: 0,
        description: "Roman-era palace complex forming the heart of the old town.",
      },
      {
        id: "split-hr-cathedral-st-domnius",
        name: "Cathedral of St Domnius",
        category: "sight",
        coords: { lat: 43.5086, lng: 16.4406 },
        price: 6,
        description: "Ancient mausoleum turned cathedral with bell tower views.",
      },
      {
        id: "split-hr-bacvice-beach",
        name: "Bačvice Beach",
        category: "nature",
        coords: { lat: 43.5039, lng: 16.447 },
        price: 0,
        description: "Sandy city beach popular for swimming and picigin.",
      },
      {
        id: "split-hr-riva-promenade",
        name: "Riva Promenade",
        category: "sight",
        coords: { lat: 43.5075, lng: 16.4383 },
        price: 0,
        description: "Palm-lined waterfront promenade for evening strolls.",
      },
      {
        id: "split-hr-marjan-hill",
        name: "Marjan Hill",
        category: "nature",
        coords: { lat: 43.5142, lng: 16.418 },
        price: 0,
        description: "Forested hill with hiking trails and viewpoints.",
      },
      {
        id: "split-hr-konoba-dinner",
        name: "Traditional Konoba",
        category: "food",
        coords: { lat: 43.509, lng: 16.4415 },
        price: 35,
        description: "Family-run konoba serving fresh Dalmatian seafood.",
      },
    ],
  },
];
