import { City } from "../types";

export const BENELUX: City[] = [
  {
    id: "amsterdam-nl",
    name: "Amsterdam",
    country: "Netherlands",
    region: "benelux",
    coords: { lat: 52.3676, lng: 4.9041 },
    climate: "temperate",
    interests: ["culture", "art", "nightlife"],
    stayPerNight: { backpacker: 45, comfort: 145, luxury: 350 },
    foodPerDay: { backpacker: 28, comfort: 65, luxury: 145 },
    minDays: 2,
    maxDays: 4,
    pois: [
      {
        id: "amsterdam-nl-anne-frank-house",
        name: "Anne Frank House",
        category: "museum",
        coords: { lat: 52.3752, lng: 4.884 },
        price: 16,
        description: "Moving museum in the house where Anne Frank hid.",
      },
      {
        id: "amsterdam-nl-rijksmuseum",
        name: "Rijksmuseum",
        category: "museum",
        coords: { lat: 52.36, lng: 4.8852 },
        price: 22,
        description: "Dutch national museum with masterworks by Rembrandt and Vermeer.",
      },
      {
        id: "amsterdam-nl-van-gogh-museum",
        name: "Van Gogh Museum",
        category: "museum",
        coords: { lat: 52.3584, lng: 4.8811 },
        price: 22,
        description: "World's largest collection of Van Gogh's works.",
      },
      {
        id: "amsterdam-nl-canal-cruise",
        name: "Canal Cruise",
        category: "activity",
        coords: { lat: 52.3702, lng: 4.8952 },
        price: 18,
        description: "Classic boat tour through Amsterdam's UNESCO canal ring.",
      },
      {
        id: "amsterdam-nl-jordaan",
        name: "Jordaan District",
        category: "sight",
        coords: { lat: 52.3746, lng: 4.8829 },
        price: 0,
        description: "Picturesque neighborhood of narrow streets and courtyards.",
      },
      {
        id: "amsterdam-nl-red-light-district",
        name: "Red Light District",
        category: "nightlife",
        coords: { lat: 52.3731, lng: 4.8994 },
        price: 0,
        description: "Historic De Wallen quarter, famed for its nightlife.",
      },
      {
        id: "amsterdam-nl-albert-cuyp-market",
        name: "Albert Cuyp Market",
        category: "food",
        coords: { lat: 52.3565, lng: 4.8917 },
        price: 10,
        description: "Bustling street market for stroopwafels and local snacks.",
      },
      {
        id: "amsterdam-nl-de-kas",
        name: "De Kas",
        category: "food",
        coords: { lat: 52.3486, lng: 4.9226 },
        price: 55,
        description: "Fine dining greenhouse restaurant with garden-to-table menus.",
      },
    ],
  },
  {
    id: "bruges-be",
    name: "Bruges",
    country: "Belgium",
    region: "benelux",
    coords: { lat: 51.2093, lng: 3.2247 },
    climate: "temperate",
    interests: ["culture", "history", "food"],
    stayPerNight: { backpacker: 33, comfort: 100, luxury: 230 },
    foodPerDay: { backpacker: 24, comfort: 50, luxury: 110 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "bruges-be-markt",
        name: "Markt Square",
        category: "sight",
        coords: { lat: 51.2085, lng: 3.2247 },
        price: 0,
        description: "Medieval market square lined with guild houses.",
      },
      {
        id: "bruges-be-belfry",
        name: "Belfry of Bruges",
        category: "sight",
        coords: { lat: 51.2083, lng: 3.2249 },
        price: 12,
        description: "Iconic 13th-century bell tower with a 366-step climb.",
      },
      {
        id: "bruges-be-canal-tour",
        name: "Canal Boat Tour",
        category: "activity",
        coords: { lat: 51.2093, lng: 3.2258 },
        price: 10,
        description: "Boat ride through Bruges' picturesque canals.",
      },
      {
        id: "bruges-be-groeninge-museum",
        name: "Groeninge Museum",
        category: "museum",
        coords: { lat: 51.2062, lng: 3.2266 },
        price: 12,
        description: "Fine arts museum with Flemish Primitives masterpieces.",
      },
      {
        id: "bruges-be-basilica-holy-blood",
        name: "Basilica of the Holy Blood",
        category: "sight",
        coords: { lat: 51.2094, lng: 3.2258 },
        price: 3,
        description: "Romanesque-Gothic basilica housing a venerated relic.",
      },
      {
        id: "bruges-be-chocolate-tasting",
        name: "Chocolate Tasting Workshop",
        category: "activity",
        coords: { lat: 51.209, lng: 3.2245 },
        price: 25,
        description: "Hands-on workshop making authentic Belgian pralines.",
      },
      {
        id: "bruges-be-de-halve-maan",
        name: "De Halve Maan Brewery",
        category: "food",
        coords: { lat: 51.2071, lng: 3.2244 },
        price: 15,
        description: "Historic family brewery with tours and tastings.",
      },
    ],
  },
  {
    id: "brussels-be",
    name: "Brussels",
    country: "Belgium",
    region: "benelux",
    coords: { lat: 50.8503, lng: 4.3517 },
    climate: "temperate",
    interests: ["culture", "food", "art"],
    stayPerNight: { backpacker: 38, comfort: 120, luxury: 270 },
    foodPerDay: { backpacker: 26, comfort: 58, luxury: 125 },
    minDays: 2,
    maxDays: 3,
    pois: [
      {
        id: "brussels-be-grand-place",
        name: "Grand Place",
        category: "sight",
        coords: { lat: 50.8467, lng: 4.3525 },
        price: 0,
        description: "Ornate UNESCO-listed central square.",
      },
      {
        id: "brussels-be-atomium",
        name: "Atomium",
        category: "sight",
        coords: { lat: 50.8949, lng: 4.3411 },
        price: 16,
        description: "Futuristic 1958 landmark shaped like an iron crystal.",
      },
      {
        id: "brussels-be-manneken-pis",
        name: "Manneken Pis",
        category: "sight",
        coords: { lat: 50.845, lng: 4.3499 },
        price: 0,
        description: "Brussels' famously whimsical bronze fountain statue.",
      },
      {
        id: "brussels-be-magritte-museum",
        name: "Magritte Museum",
        category: "museum",
        coords: { lat: 50.8434, lng: 4.3583 },
        price: 12,
        description: "Museum devoted to surrealist painter René Magritte.",
      },
      {
        id: "brussels-be-comic-strip-museum",
        name: "Belgian Comic Strip Center",
        category: "museum",
        coords: { lat: 50.85, lng: 4.354 },
        price: 12,
        description: "Celebrates Belgium's comic heritage, including Tintin.",
      },
      {
        id: "brussels-be-chez-leon",
        name: "Chez Léon",
        category: "food",
        coords: { lat: 50.8479, lng: 4.3517 },
        price: 30,
        description: "Beloved institution serving Belgian mussels and fries since 1893.",
      },
      {
        id: "brussels-be-delirium-cafe",
        name: "Delirium Café",
        category: "nightlife",
        coords: { lat: 50.846, lng: 4.3524 },
        price: 12,
        description: "Famous bar with an enormous selection of Belgian beers.",
      },
    ],
  },
];
