import { City } from "../types";

export const BRITISH_ISLES: City[] = [
  {
    id: "london-uk",
    name: "London",
    country: "United Kingdom",
    region: "british-isles",
    coords: { lat: 51.5074, lng: -0.1278 },
    climate: "cold",
    interests: ["culture", "art", "nightlife", "history"],
    stayPerNight: { backpacker: 45, comfort: 180, luxury: 400 },
    foodPerDay: { backpacker: 30, comfort: 70, luxury: 150 },
    minDays: 2,
    maxDays: 5,
    pois: [
      {
        id: "london-uk-big-ben",
        name: "Big Ben & Houses of Parliament",
        category: "sight",
        coords: { lat: 51.5007, lng: -0.1246 },
        price: 0,
        description: "Iconic clock tower at the seat of UK government.",
      },
      {
        id: "london-uk-british-museum",
        name: "British Museum",
        category: "museum",
        coords: { lat: 51.5194, lng: -0.127 },
        price: 0,
        description: "World-class collection spanning human history, free entry.",
      },
      {
        id: "london-uk-tower-of-london",
        name: "Tower of London",
        category: "sight",
        coords: { lat: 51.5081, lng: -0.0759 },
        price: 33,
        description: "Historic castle and home to the Crown Jewels.",
      },
      {
        id: "london-uk-london-eye",
        name: "London Eye",
        category: "activity",
        coords: { lat: 51.5033, lng: -0.1195 },
        price: 30,
        description: "Giant observation wheel with sweeping skyline views.",
      },
      {
        id: "london-uk-borough-market",
        name: "Borough Market",
        category: "food",
        coords: { lat: 51.5055, lng: -0.091 },
        price: 20,
        description: "Historic market packed with street food stalls.",
      },
      {
        id: "london-uk-camden-market",
        name: "Camden Market",
        category: "sight",
        coords: { lat: 51.5416, lng: -0.15 },
        price: 0,
        description: "Eclectic market famed for fashion, music and food stalls.",
      },
      {
        id: "london-uk-shoreditch-nightlife",
        name: "Shoreditch Nightlife",
        category: "nightlife",
        coords: { lat: 51.5265, lng: -0.0786 },
        price: 35,
        description: "Trendy bars, clubs and street art in East London.",
      },
    ],
  },
  {
    id: "edinburgh-uk",
    name: "Edinburgh",
    country: "United Kingdom",
    region: "british-isles",
    coords: { lat: 55.9533, lng: -3.1883 },
    climate: "cold",
    interests: ["culture", "history", "nightlife"],
    stayPerNight: { backpacker: 35, comfort: 120, luxury: 280 },
    foodPerDay: { backpacker: 25, comfort: 55, luxury: 120 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "edinburgh-uk-castle",
        name: "Edinburgh Castle",
        category: "sight",
        coords: { lat: 55.9486, lng: -3.1999 },
        price: 20,
        description: "Historic fortress dominating the city skyline.",
      },
      {
        id: "edinburgh-uk-royal-mile",
        name: "Royal Mile",
        category: "sight",
        coords: { lat: 55.95, lng: -3.1878 },
        price: 0,
        description: "Historic thoroughfare linking castle to palace.",
      },
      {
        id: "edinburgh-uk-arthurs-seat",
        name: "Arthur's Seat",
        category: "nature",
        coords: { lat: 55.9445, lng: -3.1615 },
        price: 0,
        description: "Ancient volcano with panoramic hiking trails.",
      },
      {
        id: "edinburgh-uk-national-museum",
        name: "National Museum of Scotland",
        category: "museum",
        coords: { lat: 55.947, lng: -3.1917 },
        price: 0,
        description: "Free museum covering science, art and natural history.",
      },
      {
        id: "edinburgh-uk-whisky-tour",
        name: "Scotch Whisky Experience",
        category: "activity",
        coords: { lat: 55.9497, lng: -3.1957 },
        price: 25,
        description: "Guided tasting through Scotland's famous whiskies.",
      },
      {
        id: "edinburgh-uk-old-town-pubs",
        name: "Old Town Pubs",
        category: "nightlife",
        coords: { lat: 55.949, lng: -3.193 },
        price: 30,
        description: "Historic pubs tucked into cobbled closes and vaults.",
      },
    ],
  },
  {
    id: "dublin-ie",
    name: "Dublin",
    country: "Ireland",
    region: "british-isles",
    coords: { lat: 53.3498, lng: -6.2603 },
    climate: "cold",
    interests: ["culture", "nightlife", "history"],
    stayPerNight: { backpacker: 35, comfort: 110, luxury: 260 },
    foodPerDay: { backpacker: 25, comfort: 50, luxury: 115 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "dublin-ie-trinity-college",
        name: "Trinity College",
        category: "sight",
        coords: { lat: 53.3438, lng: -6.2546 },
        price: 0,
        description: "Historic college campus with cobbled quadrangles.",
      },
      {
        id: "dublin-ie-book-of-kells",
        name: "Book of Kells Exhibition",
        category: "museum",
        coords: { lat: 53.3441, lng: -6.2551 },
        price: 18,
        description: "Ancient illuminated manuscript in the Old Library.",
      },
      {
        id: "dublin-ie-guinness-storehouse",
        name: "Guinness Storehouse",
        category: "activity",
        coords: { lat: 53.3419, lng: -6.2867 },
        price: 26,
        description: "Interactive brewery tour with rooftop bar views.",
      },
      {
        id: "dublin-ie-temple-bar",
        name: "Temple Bar",
        category: "nightlife",
        coords: { lat: 53.3454, lng: -6.2637 },
        price: 25,
        description: "Cobbled cultural quarter famed for lively pubs.",
      },
      {
        id: "dublin-ie-st-patricks-cathedral",
        name: "St Patrick's Cathedral",
        category: "sight",
        coords: { lat: 53.3395, lng: -6.2717 },
        price: 8,
        description: "Ireland's largest cathedral, founded in 1191.",
      },
      {
        id: "dublin-ie-phoenix-park",
        name: "Phoenix Park",
        category: "nature",
        coords: { lat: 53.3559, lng: -6.3298 },
        price: 0,
        description: "One of Europe's largest enclosed city parks.",
      },
    ],
  },
];
