import { City } from "../types";

export const CENTRAL: City[] = [
  {
    id: "berlin-de",
    name: "Berlin",
    country: "Germany",
    region: "central",
    coords: { lat: 52.52, lng: 13.405 },
    climate: "temperate",
    interests: ["culture", "history", "nightlife", "art"],
    stayPerNight: { backpacker: 35, comfort: 110, luxury: 260 },
    foodPerDay: { backpacker: 25, comfort: 55, luxury: 125 },
    minDays: 2,
    maxDays: 5,
    pois: [
      {
        id: "berlin-de-brandenburg-gate",
        name: "Brandenburg Gate",
        category: "sight",
        coords: { lat: 52.5163, lng: 13.3777 },
        price: 0,
        description: "Iconic 18th-century neoclassical monument.",
      },
      {
        id: "berlin-de-reichstag",
        name: "Reichstag Building",
        category: "sight",
        coords: { lat: 52.5186, lng: 13.3762 },
        price: 0,
        description: "Historic parliament with a glass dome and city views.",
      },
      {
        id: "berlin-de-museum-island",
        name: "Museum Island",
        category: "museum",
        coords: { lat: 52.5169, lng: 13.3979 },
        price: 19,
        description: "UNESCO cluster of five world-class museums.",
      },
      {
        id: "berlin-de-east-side-gallery",
        name: "East Side Gallery",
        category: "sight",
        coords: { lat: 52.505, lng: 13.4394 },
        price: 0,
        description: "Longest remaining stretch of the Berlin Wall, covered in murals.",
      },
      {
        id: "berlin-de-checkpoint-charlie",
        name: "Checkpoint Charlie",
        category: "sight",
        coords: { lat: 52.5076, lng: 13.3904 },
        price: 0,
        description: "Famous Cold War-era border crossing point.",
      },
      {
        id: "berlin-de-berghain",
        name: "Berghain",
        category: "nightlife",
        coords: { lat: 52.5109, lng: 13.4433 },
        price: 20,
        description: "World-renowned techno club in a former power plant.",
      },
      {
        id: "berlin-de-curry36",
        name: "Curry 36",
        category: "food",
        coords: { lat: 52.4991, lng: 13.3833 },
        price: 8,
        description: "Legendary currywurst stand loved by locals.",
      },
      {
        id: "berlin-de-tiergarten",
        name: "Tiergarten",
        category: "nature",
        coords: { lat: 52.5145, lng: 13.3501 },
        price: 0,
        description: "Sprawling central park ideal for walks and picnics.",
      },
    ],
  },
  {
    id: "munich-de",
    name: "Munich",
    country: "Germany",
    region: "central",
    coords: { lat: 48.1351, lng: 11.582 },
    climate: "cold",
    interests: ["culture", "food", "history"],
    stayPerNight: { backpacker: 42, comfort: 135, luxury: 320 },
    foodPerDay: { backpacker: 28, comfort: 62, luxury: 145 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "munich-de-marienplatz",
        name: "Marienplatz",
        category: "sight",
        coords: { lat: 48.1374, lng: 11.5755 },
        price: 0,
        description: "Central square with the Glockenspiel and New Town Hall.",
      },
      {
        id: "munich-de-english-garden",
        name: "English Garden",
        category: "nature",
        coords: { lat: 48.1642, lng: 11.6056 },
        price: 0,
        description: "Vast park larger than New York's Central Park.",
      },
      {
        id: "munich-de-nymphenburg",
        name: "Nymphenburg Palace",
        category: "museum",
        coords: { lat: 48.1583, lng: 11.5033 },
        price: 8,
        description: "Baroque summer palace of Bavarian royalty.",
      },
      {
        id: "munich-de-hofbrauhaus",
        name: "Hofbräuhaus",
        category: "food",
        coords: { lat: 48.1374, lng: 11.5799 },
        price: 35,
        description: "World-famous beer hall with live oompah music.",
      },
      {
        id: "munich-de-viktualienmarkt",
        name: "Viktualienmarkt",
        category: "food",
        coords: { lat: 48.1351, lng: 11.5761 },
        price: 15,
        description: "Historic daily food market in the city center.",
      },
      {
        id: "munich-de-deutsches-museum",
        name: "Deutsches Museum",
        category: "museum",
        coords: { lat: 48.1299, lng: 11.5836 },
        price: 15,
        description: "One of the world's largest science and technology museums.",
      },
      {
        id: "munich-de-frauenkirche",
        name: "Frauenkirche",
        category: "sight",
        coords: { lat: 48.1385, lng: 11.5737 },
        price: 0,
        description: "Twin-domed Gothic cathedral, Munich's symbol.",
      },
    ],
  },
  {
    id: "prague-cz",
    name: "Prague",
    country: "Czech Republic",
    region: "central",
    coords: { lat: 50.0755, lng: 14.4378 },
    climate: "cold",
    interests: ["history", "culture", "nightlife"],
    stayPerNight: { backpacker: 25, comfort: 80, luxury: 200 },
    foodPerDay: { backpacker: 20, comfort: 45, luxury: 100 },
    minDays: 2,
    maxDays: 4,
    pois: [
      {
        id: "prague-cz-charles-bridge",
        name: "Charles Bridge",
        category: "sight",
        coords: { lat: 50.0865, lng: 14.4114 },
        price: 0,
        description: "Historic stone bridge lined with baroque statues.",
      },
      {
        id: "prague-cz-prague-castle",
        name: "Prague Castle",
        category: "sight",
        coords: { lat: 50.091, lng: 14.4016 },
        price: 15,
        description: "The largest ancient castle complex in the world.",
      },
      {
        id: "prague-cz-old-town-square",
        name: "Old Town Square",
        category: "sight",
        coords: { lat: 50.087, lng: 14.4207 },
        price: 0,
        description: "Medieval square surrounded by colorful facades.",
      },
      {
        id: "prague-cz-astronomical-clock",
        name: "Astronomical Clock",
        category: "sight",
        coords: { lat: 50.087, lng: 14.4208 },
        price: 3,
        description: "Medieval clock with an hourly parade of figures.",
      },
      {
        id: "prague-cz-jewish-quarter",
        name: "Jewish Quarter (Josefov)",
        category: "museum",
        coords: { lat: 50.0908, lng: 14.4187 },
        price: 18,
        description: "Historic Jewish district with synagogues and cemetery.",
      },
      {
        id: "prague-cz-beer-museum",
        name: "Prague Beer Museum",
        category: "nightlife",
        coords: { lat: 50.088, lng: 14.418 },
        price: 12,
        description: "Tasting tour through Czech craft beer culture.",
      },
      {
        id: "prague-cz-lokal",
        name: "Lokál",
        category: "food",
        coords: { lat: 50.0891, lng: 14.4249 },
        price: 18,
        description: "Beloved pub serving classic Czech dishes and fresh Pilsner.",
      },
      {
        id: "prague-cz-vltava-cruise",
        name: "Vltava River Cruise",
        category: "activity",
        coords: { lat: 50.084, lng: 14.41 },
        price: 20,
        description: "Scenic river cruise past Prague's landmarks.",
      },
    ],
  },
  {
    id: "vienna-at",
    name: "Vienna",
    country: "Austria",
    region: "central",
    coords: { lat: 48.2082, lng: 16.3738 },
    climate: "temperate",
    interests: ["culture", "history", "art"],
    stayPerNight: { backpacker: 38, comfort: 125, luxury: 290 },
    foodPerDay: { backpacker: 27, comfort: 58, luxury: 130 },
    minDays: 2,
    maxDays: 5,
    pois: [
      {
        id: "vienna-at-schonbrunn",
        name: "Schönbrunn Palace",
        category: "museum",
        coords: { lat: 48.1855, lng: 16.3122 },
        price: 24,
        description: "Former imperial summer residence with lavish gardens.",
      },
      {
        id: "vienna-at-stephansdom",
        name: "St. Stephen's Cathedral",
        category: "sight",
        coords: { lat: 48.2085, lng: 16.3731 },
        price: 6,
        description: "Vienna's gothic cathedral and spiritual heart.",
      },
      {
        id: "vienna-at-belvedere",
        name: "Belvedere Palace",
        category: "museum",
        coords: { lat: 48.1913, lng: 16.3805 },
        price: 19,
        description: "Baroque palace housing Klimt's 'The Kiss'.",
      },
      {
        id: "vienna-at-naschmarkt",
        name: "Naschmarkt",
        category: "food",
        coords: { lat: 48.1974, lng: 16.3639 },
        price: 15,
        description: "Vienna's largest and most vibrant food market.",
      },
      {
        id: "vienna-at-prater",
        name: "Prater",
        category: "activity",
        coords: { lat: 48.2166, lng: 16.4033 },
        price: 5,
        description: "Historic amusement park with the iconic Giant Wheel.",
      },
      {
        id: "vienna-at-cafe-central",
        name: "Café Central",
        category: "food",
        coords: { lat: 48.2103, lng: 16.3659 },
        price: 20,
        description: "Grand 19th-century coffeehouse once frequented by intellectuals.",
      },
      {
        id: "vienna-at-state-opera",
        name: "Vienna State Opera",
        category: "sight",
        coords: { lat: 48.2035, lng: 16.369 },
        price: 15,
        description: "World-class opera house with standing-room tickets.",
      },
    ],
  },
  {
    id: "budapest-hu",
    name: "Budapest",
    country: "Hungary",
    region: "central",
    coords: { lat: 47.4979, lng: 19.0402 },
    climate: "temperate",
    interests: ["culture", "nightlife", "history"],
    stayPerNight: { backpacker: 26, comfort: 82, luxury: 205 },
    foodPerDay: { backpacker: 20, comfort: 46, luxury: 102 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "budapest-hu-parliament",
        name: "Hungarian Parliament Building",
        category: "sight",
        coords: { lat: 47.5076, lng: 19.0458 },
        price: 15,
        description: "Monumental neo-gothic building on the Danube.",
      },
      {
        id: "budapest-hu-fishermans-bastion",
        name: "Fisherman's Bastion",
        category: "sight",
        coords: { lat: 47.5023, lng: 19.0347 },
        price: 3,
        description: "Terrace with fairy-tale turrets and river views.",
      },
      {
        id: "budapest-hu-szechenyi-baths",
        name: "Széchenyi Thermal Bath",
        category: "activity",
        coords: { lat: 47.5183, lng: 19.0822 },
        price: 22,
        description: "Grand neo-baroque thermal spa complex.",
      },
      {
        id: "budapest-hu-ruin-bars",
        name: "Szimpla Kert",
        category: "nightlife",
        coords: { lat: 47.4979, lng: 19.0653 },
        price: 10,
        description: "Iconic ruin bar in a decaying courtyard building.",
      },
      {
        id: "budapest-hu-buda-castle",
        name: "Buda Castle",
        category: "museum",
        coords: { lat: 47.4961, lng: 19.0398 },
        price: 12,
        description: "Historic royal palace overlooking the city.",
      },
      {
        id: "budapest-hu-central-market",
        name: "Great Market Hall",
        category: "food",
        coords: { lat: 47.4867, lng: 19.0605 },
        price: 10,
        description: "Budapest's largest and oldest indoor market.",
      },
      {
        id: "budapest-hu-new-york-cafe",
        name: "New York Café",
        category: "food",
        coords: { lat: 47.4989, lng: 19.0745 },
        price: 25,
        description: "Opulent 19th-century café dubbed 'the most beautiful in the world'.",
      },
    ],
  },
  {
    id: "zurich-ch",
    name: "Zurich",
    country: "Switzerland",
    region: "central",
    coords: { lat: 47.3769, lng: 8.5417 },
    climate: "cold",
    interests: ["nature", "adventure", "culture"],
    stayPerNight: { backpacker: 50, comfort: 150, luxury: 400 },
    foodPerDay: { backpacker: 30, comfort: 70, luxury: 160 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "zurich-ch-old-town",
        name: "Zurich Old Town",
        category: "sight",
        coords: { lat: 47.3717, lng: 8.5426 },
        price: 0,
        description: "Charming medieval streets along the Limmat river.",
      },
      {
        id: "zurich-ch-lake-zurich",
        name: "Lake Zurich",
        category: "nature",
        coords: { lat: 47.3593, lng: 8.5468 },
        price: 0,
        description: "Scenic lakefront for walks, swimming, and boat rides.",
      },
      {
        id: "zurich-ch-uetliberg",
        name: "Uetliberg",
        category: "nature",
        coords: { lat: 47.3487, lng: 8.4913 },
        price: 10,
        description: "Panoramic mountain ridge overlooking the city and Alps.",
      },
      {
        id: "zurich-ch-grossmunster",
        name: "Grossmünster",
        category: "sight",
        coords: { lat: 47.3702, lng: 8.5441 },
        price: 5,
        description: "Twin-towered Romanesque church with tower views.",
      },
      {
        id: "zurich-ch-kunsthaus",
        name: "Kunsthaus Zürich",
        category: "museum",
        coords: { lat: 47.3707, lng: 8.5484 },
        price: 23,
        description: "Leading Swiss art museum with an extensive collection.",
      },
      {
        id: "zurich-ch-bahnhofstrasse",
        name: "Bahnhofstrasse",
        category: "sight",
        coords: { lat: 47.3745, lng: 8.5379 },
        price: 0,
        description: "One of the world's most exclusive shopping streets.",
      },
      {
        id: "zurich-ch-swiss-national-museum",
        name: "Swiss National Museum",
        category: "museum",
        coords: { lat: 47.3782, lng: 8.5402 },
        price: 10,
        description: "Castle-like museum covering Swiss cultural history.",
      },
    ],
  },
];
