import { City } from "../types";

export const EAST: City[] = [
  {
    id: "krakow-pl",
    name: "Krakow",
    country: "Poland",
    region: "east",
    coords: { lat: 50.0647, lng: 19.945 },
    climate: "cold",
    interests: ["history", "culture", "food"],
    stayPerNight: { backpacker: 22, comfort: 70, luxury: 170 },
    foodPerDay: { backpacker: 18, comfort: 38, luxury: 85 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "krakow-pl-main-square",
        name: "Main Market Square",
        category: "sight",
        coords: { lat: 50.0617, lng: 19.9373 },
        price: 0,
        description: "Grand medieval square, one of Europe's largest.",
      },
      {
        id: "krakow-pl-wawel-castle",
        name: "Wawel Castle",
        category: "sight",
        coords: { lat: 50.0544, lng: 19.9354 },
        price: 20,
        description: "Royal castle overlooking the Vistula River.",
      },
      {
        id: "krakow-pl-auschwitz-tour",
        name: "Auschwitz-Birkenau Memorial Tour",
        category: "activity",
        coords: { lat: 50.0359, lng: 19.1728 },
        price: 30,
        description: "Guided tour to the sobering WWII memorial site.",
      },
      {
        id: "krakow-pl-kazimierz",
        name: "Kazimierz",
        category: "sight",
        coords: { lat: 50.0508, lng: 19.9455 },
        price: 0,
        description: "Historic Jewish quarter with lively bars and cafés.",
      },
      {
        id: "krakow-pl-cloth-hall",
        name: "Cloth Hall",
        category: "museum",
        coords: { lat: 50.0617, lng: 19.9373 },
        price: 6,
        description: "Renaissance trading hall with a gallery of Polish art.",
      },
      {
        id: "krakow-pl-milk-bar",
        name: "Milk Bar",
        category: "food",
        coords: { lat: 50.0625, lng: 19.938 },
        price: 12,
        description: "Classic milk bar serving cheap, hearty Polish food.",
      },
    ],
  },
  {
    id: "warsaw-pl",
    name: "Warsaw",
    country: "Poland",
    region: "east",
    coords: { lat: 52.2297, lng: 21.0122 },
    climate: "cold",
    interests: ["history", "culture", "nightlife"],
    stayPerNight: { backpacker: 25, comfort: 75, luxury: 180 },
    foodPerDay: { backpacker: 18, comfort: 40, luxury: 90 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "warsaw-pl-old-town",
        name: "Old Town Market Square",
        category: "sight",
        coords: { lat: 52.2496, lng: 21.0122 },
        price: 0,
        description: "Meticulously rebuilt UNESCO old town square.",
      },
      {
        id: "warsaw-pl-royal-castle",
        name: "Royal Castle",
        category: "museum",
        coords: { lat: 52.2478, lng: 21.0145 },
        price: 10,
        description: "Former royal residence with lavish state rooms.",
      },
      {
        id: "warsaw-pl-uprising-museum",
        name: "Warsaw Uprising Museum",
        category: "museum",
        coords: { lat: 52.2333, lng: 20.9829 },
        price: 8,
        description: "Powerful museum on the 1944 Warsaw Uprising.",
      },
      {
        id: "warsaw-pl-lazienki-park",
        name: "Łazienki Park",
        category: "nature",
        coords: { lat: 52.2151, lng: 21.0353 },
        price: 0,
        description: "Elegant royal park with a palace on the water.",
      },
      {
        id: "warsaw-pl-vistula-boulevards",
        name: "Vistula Boulevards",
        category: "nightlife",
        coords: { lat: 52.241, lng: 21.033 },
        price: 20,
        description: "Riverside bars, food trucks and summer nightlife.",
      },
      {
        id: "warsaw-pl-bar-mleczny",
        name: "Bar Mleczny",
        category: "food",
        coords: { lat: 52.238, lng: 21.015 },
        price: 12,
        description: "Budget-friendly milk bar serving traditional dishes.",
      },
    ],
  },
  {
    id: "ljubljana-si",
    name: "Ljubljana",
    country: "Slovenia",
    region: "east",
    coords: { lat: 46.0569, lng: 14.5058 },
    climate: "temperate",
    interests: ["nature", "culture", "food"],
    stayPerNight: { backpacker: 28, comfort: 85, luxury: 190 },
    foodPerDay: { backpacker: 20, comfort: 42, luxury: 95 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "ljubljana-si-old-town",
        name: "Ljubljana Old Town",
        category: "sight",
        coords: { lat: 46.0508, lng: 14.5069 },
        price: 0,
        description: "Charming riverside old town beneath the castle.",
      },
      {
        id: "ljubljana-si-castle",
        name: "Ljubljana Castle",
        category: "sight",
        coords: { lat: 46.0489, lng: 14.5083 },
        price: 12,
        description: "Hilltop castle with funicular access and city views.",
      },
      {
        id: "ljubljana-si-triple-bridge",
        name: "Triple Bridge",
        category: "sight",
        coords: { lat: 46.0511, lng: 14.5064 },
        price: 0,
        description: "Iconic trio of pedestrian bridges over the Ljubljanica.",
      },
      {
        id: "ljubljana-si-tivoli-park",
        name: "Tivoli Park",
        category: "nature",
        coords: { lat: 46.0561, lng: 14.4936 },
        price: 0,
        description: "The city's largest park, ideal for a relaxed walk.",
      },
      {
        id: "ljubljana-si-central-market",
        name: "Central Market",
        category: "food",
        coords: { lat: 46.0517, lng: 14.5075 },
        price: 15,
        description: "Riverside market for local produce and street food.",
      },
      {
        id: "ljubljana-si-dragon-bridge",
        name: "Dragon Bridge",
        category: "sight",
        coords: { lat: 46.0525, lng: 14.5089 },
        price: 0,
        description: "Art Nouveau bridge guarded by four dragon statues.",
      },
    ],
  },
];
