import { City } from "../types";

export const FRANCE: City[] = [
  {
    id: "paris-fr",
    name: "Paris",
    country: "France",
    region: "france",
    coords: { lat: 48.8566, lng: 2.3522 },
    climate: "temperate",
    interests: ["culture", "food", "art"],
    stayPerNight: { backpacker: 45, comfort: 140, luxury: 380 },
    foodPerDay: { backpacker: 30, comfort: 65, luxury: 150 },
    minDays: 2,
    maxDays: 5,
    pois: [
      {
        id: "paris-eiffel-tower",
        name: "Eiffel Tower",
        category: "sight",
        coords: { lat: 48.8584, lng: 2.2945 },
        price: 22,
        description: "Iconic landmark with panoramic city views.",
      },
      {
        id: "paris-louvre",
        name: "Louvre Museum",
        category: "museum",
        coords: { lat: 48.8606, lng: 2.3376 },
        price: 17,
        description: "World-famous museum housing the Mona Lisa.",
      },
      {
        id: "paris-le-marais",
        name: "Le Marais",
        category: "sight",
        coords: { lat: 48.8575, lng: 2.3622 },
        price: 0,
        description: "Historic district with boutiques and cafés.",
      },
      {
        id: "paris-seine-cruise",
        name: "Seine River Cruise",
        category: "activity",
        coords: { lat: 48.8592, lng: 2.3413 },
        price: 16,
        description: "Scenic cruise, best enjoyed at sunset.",
      },
      {
        id: "paris-comptoir-relais",
        name: "Le Comptoir du Relais",
        category: "food",
        coords: { lat: 48.852, lng: 2.3387 },
        price: 40,
        description: "Classic Parisian bistro experience.",
      },
      {
        id: "paris-montmartre",
        name: "Montmartre & Sacré-Cœur",
        category: "sight",
        coords: { lat: 48.8867, lng: 2.3431 },
        price: 0,
        description: "Bohemian hilltop quarter with basilica views.",
      },
    ],
  },
  {
    id: "lyon-fr",
    name: "Lyon",
    country: "France",
    region: "france",
    coords: { lat: 45.764, lng: 4.8357 },
    climate: "temperate",
    interests: ["food", "culture"],
    stayPerNight: { backpacker: 35, comfort: 100, luxury: 240 },
    foodPerDay: { backpacker: 25, comfort: 55, luxury: 120 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "lyon-vieux-lyon",
        name: "Vieux Lyon",
        category: "sight",
        coords: { lat: 45.7625, lng: 4.8275 },
        price: 0,
        description: "UNESCO old town with Renaissance charm.",
      },
      {
        id: "lyon-fourviere",
        name: "Fourvière Basilica",
        category: "sight",
        coords: { lat: 45.7623, lng: 4.8226 },
        price: 0,
        description: "Hilltop basilica with panoramic views.",
      },
      {
        id: "lyon-traboules",
        name: "Traboules",
        category: "sight",
        coords: { lat: 45.767, lng: 4.832 },
        price: 0,
        description: "Hidden passageways unique to Lyon.",
      },
      {
        id: "lyon-halles-bocuse",
        name: "Les Halles Bocuse",
        category: "food",
        coords: { lat: 45.7621, lng: 4.8512 },
        price: 30,
        description: "Premium indoor food market.",
      },
      {
        id: "lyon-rhone-walk",
        name: "Rhône River Walk",
        category: "activity",
        coords: { lat: 45.7588, lng: 4.84 },
        price: 0,
        description: "Perfect for biking or relaxing strolls.",
      },
    ],
  },
  {
    id: "marseille-fr",
    name: "Marseille",
    country: "France",
    region: "france",
    coords: { lat: 43.2965, lng: 5.3698 },
    climate: "warm",
    interests: ["food", "nature", "culture"],
    stayPerNight: { backpacker: 32, comfort: 95, luxury: 220 },
    foodPerDay: { backpacker: 25, comfort: 50, luxury: 110 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "marseille-old-port",
        name: "Old Port",
        category: "sight",
        coords: { lat: 43.2951, lng: 5.374 },
        price: 0,
        description: "Historic harbor and vibrant center.",
      },
      {
        id: "marseille-calanques",
        name: "Calanques National Park",
        category: "nature",
        coords: { lat: 43.214, lng: 5.4542 },
        price: 0,
        description: "Stunning cliffs and turquoise waters.",
      },
      {
        id: "marseille-le-panier",
        name: "Le Panier",
        category: "sight",
        coords: { lat: 43.2995, lng: 5.3678 },
        price: 0,
        description: "Colorful historic neighborhood.",
      },
      {
        id: "marseille-boat-tour",
        name: "Boat Tour Calanques",
        category: "activity",
        coords: { lat: 43.2938, lng: 5.3705 },
        price: 35,
        description: "Best way to explore hidden coves.",
      },
      {
        id: "marseille-chez-etienne",
        name: "Chez Etienne",
        category: "food",
        coords: { lat: 43.298, lng: 5.3695 },
        price: 28,
        description: "Famous for traditional Marseille cuisine.",
      },
    ],
  },
  {
    id: "nice-fr",
    name: "Nice",
    country: "France",
    region: "france",
    coords: { lat: 43.7102, lng: 7.262 },
    climate: "warm",
    interests: ["beach", "nature", "food"],
    stayPerNight: { backpacker: 40, comfort: 120, luxury: 300 },
    foodPerDay: { backpacker: 28, comfort: 60, luxury: 140 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "nice-promenade",
        name: "Promenade des Anglais",
        category: "sight",
        coords: { lat: 43.6942, lng: 7.2514 },
        price: 0,
        description: "Seafront boulevard with iconic views.",
      },
      {
        id: "nice-vieux-nice",
        name: "Vieux Nice",
        category: "sight",
        coords: { lat: 43.6967, lng: 7.275 },
        price: 0,
        description: "Old town with colorful streets and markets.",
      },
      {
        id: "nice-castle-hill",
        name: "Castle Hill",
        category: "nature",
        coords: { lat: 43.6944, lng: 7.2794 },
        price: 0,
        description: "Best panoramic viewpoint.",
      },
      {
        id: "nice-cours-saleya",
        name: "Cours Saleya Market",
        category: "food",
        coords: { lat: 43.6953, lng: 7.273 },
        price: 15,
        description: "Famous flower and food market.",
      },
      {
        id: "nice-petite-maison",
        name: "La Petite Maison",
        category: "food",
        coords: { lat: 43.6958, lng: 7.2678 },
        price: 60,
        description: "Top-rated Mediterranean cuisine.",
      },
    ],
  },
  {
    id: "bordeaux-fr",
    name: "Bordeaux",
    country: "France",
    region: "france",
    coords: { lat: 44.8378, lng: -0.5792 },
    climate: "temperate",
    interests: ["food", "culture"],
    stayPerNight: { backpacker: 35, comfort: 105, luxury: 250 },
    foodPerDay: { backpacker: 25, comfort: 55, luxury: 125 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "bordeaux-place-bourse",
        name: "Place de la Bourse",
        category: "sight",
        coords: { lat: 44.8417, lng: -0.5701 },
        price: 0,
        description: "Iconic square with water mirror.",
      },
      {
        id: "bordeaux-cite-du-vin",
        name: "Cité du Vin",
        category: "museum",
        coords: { lat: 44.8624, lng: -0.55 },
        price: 22,
        description: "Interactive wine museum.",
      },
      {
        id: "bordeaux-old-town",
        name: "Old Town",
        category: "sight",
        coords: { lat: 44.8385, lng: -0.574 },
        price: 0,
        description: "Elegant streets and architecture.",
      },
      {
        id: "bordeaux-wine-tour",
        name: "Wine Tasting Tour",
        category: "activity",
        coords: { lat: 44.837, lng: -0.579 },
        price: 55,
        description: "Explore nearby vineyards.",
      },
      {
        id: "bordeaux-chapon-fin",
        name: "Le Chapon Fin",
        category: "food",
        coords: { lat: 44.8421, lng: -0.5775 },
        price: 55,
        description: "Historic fine dining restaurant.",
      },
    ],
  },
  {
    id: "toulouse-fr",
    name: "Toulouse",
    country: "France",
    region: "france",
    coords: { lat: 43.6047, lng: 1.4442 },
    climate: "temperate",
    interests: ["culture", "food"],
    stayPerNight: { backpacker: 30, comfort: 90, luxury: 210 },
    foodPerDay: { backpacker: 22, comfort: 48, luxury: 105 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "toulouse-capitole",
        name: "Place du Capitole",
        category: "sight",
        coords: { lat: 43.6044, lng: 1.444 },
        price: 0,
        description: "Main square and historic center.",
      },
      {
        id: "toulouse-saint-sernin",
        name: "Basilica Saint-Sernin",
        category: "sight",
        coords: { lat: 43.6085, lng: 1.4418 },
        price: 0,
        description: "UNESCO Romanesque church.",
      },
      {
        id: "toulouse-garonne-walk",
        name: "Garonne River Walk",
        category: "activity",
        coords: { lat: 43.601, lng: 1.437 },
        price: 0,
        description: "Relaxing riverside stroll.",
      },
      {
        id: "toulouse-victor-hugo-market",
        name: "Victor Hugo Market",
        category: "food",
        coords: { lat: 43.6075, lng: 1.447 },
        price: 15,
        description: "Best local food market.",
      },
      {
        id: "toulouse-le-bibent",
        name: "Le Bibent",
        category: "food",
        coords: { lat: 43.6045, lng: 1.4435 },
        price: 40,
        description: "Elegant brasserie with local dishes.",
      },
    ],
  },
  {
    id: "strasbourg-fr",
    name: "Strasbourg",
    country: "France",
    region: "france",
    coords: { lat: 48.5734, lng: 7.7521 },
    climate: "cold",
    interests: ["culture", "history"],
    stayPerNight: { backpacker: 33, comfort: 100, luxury: 230 },
    foodPerDay: { backpacker: 24, comfort: 50, luxury: 110 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "strasbourg-cathedral",
        name: "Strasbourg Cathedral",
        category: "sight",
        coords: { lat: 48.5819, lng: 7.7508 },
        price: 0,
        description: "Gothic masterpiece.",
      },
      {
        id: "strasbourg-petite-france",
        name: "La Petite France",
        category: "sight",
        coords: { lat: 48.581, lng: 7.742 },
        price: 0,
        description: "Charming canals and half-timbered houses.",
      },
      {
        id: "strasbourg-boat-tour",
        name: "Boat Tour",
        category: "activity",
        coords: { lat: 48.5805, lng: 7.749 },
        price: 15,
        description: "Explore the city via canals.",
      },
      {
        id: "strasbourg-christmas-market",
        name: "Christmas Market",
        category: "sight",
        coords: { lat: 48.5839, lng: 7.748 },
        price: 0,
        description: "One of Europe's oldest markets.",
      },
      {
        id: "strasbourg-maison-kammerzell",
        name: "Maison Kammerzell",
        category: "food",
        coords: { lat: 48.582, lng: 7.7501 },
        price: 45,
        description: "Historic Alsatian restaurant.",
      },
    ],
  },
  {
    id: "nantes-fr",
    name: "Nantes",
    country: "France",
    region: "france",
    coords: { lat: 47.2184, lng: -1.5536 },
    climate: "temperate",
    interests: ["culture", "nature"],
    stayPerNight: { backpacker: 30, comfort: 85, luxury: 200 },
    foodPerDay: { backpacker: 22, comfort: 45, luxury: 100 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "nantes-machines",
        name: "Machines of the Isle",
        category: "activity",
        coords: { lat: 47.2064, lng: -1.5643 },
        price: 12,
        description: "Giant mechanical elephant attraction.",
      },
      {
        id: "nantes-chateau",
        name: "Château des Ducs de Bretagne",
        category: "museum",
        coords: { lat: 47.2163, lng: -1.5492 },
        price: 9,
        description: "Historic castle museum.",
      },
      {
        id: "nantes-ile-de-nantes",
        name: "Île de Nantes",
        category: "sight",
        coords: { lat: 47.205, lng: -1.555 },
        price: 0,
        description: "Creative and cultural hub.",
      },
      {
        id: "nantes-loire-walk",
        name: "Loire River Walk",
        category: "nature",
        coords: { lat: 47.212, lng: -1.56 },
        price: 0,
        description: "Scenic riverside paths.",
      },
      {
        id: "nantes-la-cigale",
        name: "La Cigale",
        category: "food",
        coords: { lat: 47.2138, lng: -1.5615 },
        price: 35,
        description: "Famous Belle Époque brasserie.",
      },
    ],
  },
  {
    id: "annecy-fr",
    name: "Annecy",
    country: "France",
    region: "france",
    coords: { lat: 45.8992, lng: 6.1294 },
    climate: "cold",
    interests: ["nature", "adventure"],
    stayPerNight: { backpacker: 38, comfort: 110, luxury: 260 },
    foodPerDay: { backpacker: 26, comfort: 55, luxury: 120 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "annecy-lake",
        name: "Lake Annecy",
        category: "nature",
        coords: { lat: 45.86, lng: 6.17 },
        price: 0,
        description: "Crystal-clear alpine lake.",
      },
      {
        id: "annecy-old-town",
        name: "Old Town",
        category: "sight",
        coords: { lat: 45.899, lng: 6.126 },
        price: 0,
        description: "Canals and pastel-colored houses.",
      },
      {
        id: "annecy-cycling-loop",
        name: "Cycling Lake Loop",
        category: "activity",
        coords: { lat: 45.88, lng: 6.15 },
        price: 20,
        description: "Popular scenic bike route.",
      },
      {
        id: "annecy-boat-cruise",
        name: "Boat Cruise",
        category: "activity",
        coords: { lat: 45.898, lng: 6.131 },
        price: 18,
        description: "Relaxing lake experience.",
      },
      {
        id: "annecy-le-freti",
        name: "Le Freti",
        category: "food",
        coords: { lat: 45.8987, lng: 6.1268 },
        price: 30,
        description: "Famous for fondue and Savoy cuisine.",
      },
    ],
  },
  {
    id: "cannes-fr",
    name: "Cannes",
    country: "France",
    region: "france",
    coords: { lat: 43.5528, lng: 7.0174 },
    climate: "warm",
    interests: ["nightlife", "beach", "culture"],
    stayPerNight: { backpacker: 45, comfort: 150, luxury: 400 },
    foodPerDay: { backpacker: 30, comfort: 70, luxury: 160 },
    minDays: 1,
    maxDays: 2,
    pois: [
      {
        id: "cannes-croisette",
        name: "La Croisette",
        category: "sight",
        coords: { lat: 43.548, lng: 7.03 },
        price: 0,
        description: "Luxury promenade by the sea.",
      },
      {
        id: "cannes-palais-festivals",
        name: "Palais des Festivals",
        category: "sight",
        coords: { lat: 43.551, lng: 7.0177 },
        price: 0,
        description: "Home of Cannes Film Festival.",
      },
      {
        id: "cannes-le-suquet",
        name: "Le Suquet",
        category: "sight",
        coords: { lat: 43.5505, lng: 7.011 },
        price: 0,
        description: "Historic old quarter.",
      },
      {
        id: "cannes-beach-clubs",
        name: "Beach Clubs",
        category: "nightlife",
        coords: { lat: 43.547, lng: 7.035 },
        price: 40,
        description: "Relax on private beaches.",
      },
      {
        id: "cannes-la-mome",
        name: "La Môme",
        category: "food",
        coords: { lat: 43.5522, lng: 7.0225 },
        price: 65,
        description: "Trendy upscale restaurant.",
      },
    ],
  },
];
