import { City } from "../types";

export const IBERIA: City[] = [
  {
    id: "lisbon-pt",
    name: "Lisbon",
    country: "Portugal",
    region: "iberia",
    coords: { lat: 38.7223, lng: -9.1393 },
    climate: "warm",
    interests: ["culture", "food", "history", "nightlife"],
    stayPerNight: { backpacker: 28, comfort: 85, luxury: 220 },
    foodPerDay: { backpacker: 22, comfort: 48, luxury: 110 },
    minDays: 2,
    maxDays: 4,
    pois: [
      {
        id: "lisbon-belem-tower",
        name: "Belém Tower",
        category: "sight",
        coords: { lat: 38.6916, lng: -9.216 },
        price: 6,
        description: "Iconic Manueline tower guarding the Tagus estuary.",
      },
      {
        id: "lisbon-jeronimos",
        name: "Jerónimos Monastery",
        category: "museum",
        coords: { lat: 38.6979, lng: -9.2068 },
        price: 10,
        description: "Grand UNESCO monastery near the riverfront.",
      },
      {
        id: "lisbon-alfama",
        name: "Alfama District",
        category: "sight",
        coords: { lat: 38.7139, lng: -9.1292 },
        price: 0,
        description: "Oldest quarter with narrow lanes and fado bars.",
      },
      {
        id: "lisbon-lx-factory",
        name: "LX Factory",
        category: "activity",
        coords: { lat: 38.7043, lng: -9.1774 },
        price: 0,
        description: "Creative hub of shops, murals, and cafés.",
      },
      {
        id: "lisbon-time-out-market",
        name: "Time Out Market",
        category: "food",
        coords: { lat: 38.7069, lng: -9.1459 },
        price: 25,
        description: "Food hall gathering the city's best kitchens.",
      },
      {
        id: "lisbon-fado-house",
        name: "Fado Dinner Show",
        category: "nightlife",
        coords: { lat: 38.7115, lng: -9.1425 },
        price: 30,
        description: "Traditional Portuguese music with dinner.",
      },
      {
        id: "lisbon-tram28",
        name: "Tram 28 Ride",
        category: "activity",
        coords: { lat: 38.7106, lng: -9.1305 },
        price: 3,
        description: "Historic tram winding through the old hills.",
      },
    ],
  },
  {
    id: "porto-pt",
    name: "Porto",
    country: "Portugal",
    region: "iberia",
    coords: { lat: 41.1579, lng: -8.6291 },
    climate: "temperate",
    interests: ["food", "culture", "history"],
    stayPerNight: { backpacker: 25, comfort: 75, luxury: 190 },
    foodPerDay: { backpacker: 20, comfort: 42, luxury: 95 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "porto-livraria-lello",
        name: "Livraria Lello",
        category: "sight",
        coords: { lat: 41.1469, lng: -8.6147 },
        price: 8,
        description: "Ornate neo-Gothic bookstore, a Porto icon.",
      },
      {
        id: "porto-ribeira",
        name: "Ribeira District",
        category: "sight",
        coords: { lat: 41.1408, lng: -8.611 },
        price: 0,
        description: "Riverside old town with colorful houses.",
      },
      {
        id: "porto-clerigos-tower",
        name: "Clérigos Tower",
        category: "sight",
        coords: { lat: 41.1455, lng: -8.6155 },
        price: 6,
        description: "Baroque tower with sweeping city views.",
      },
      {
        id: "porto-port-wine-cellars",
        name: "Port Wine Cellar Tour",
        category: "activity",
        coords: { lat: 41.1355, lng: -8.6113 },
        price: 15,
        description: "Tastings in Vila Nova de Gaia's historic lodges.",
      },
      {
        id: "porto-douro-cruise",
        name: "Douro River Cruise",
        category: "activity",
        coords: { lat: 41.1395, lng: -8.608 },
        price: 20,
        description: "Scenic cruise beneath Porto's six bridges.",
      },
      {
        id: "porto-bolhao-market",
        name: "Mercado do Bolhão",
        category: "food",
        coords: { lat: 41.1495, lng: -8.6055 },
        price: 15,
        description: "Restored market for local produce and bites.",
      },
      {
        id: "porto-cafe-santiago",
        name: "Café Santiago",
        category: "food",
        coords: { lat: 41.1477, lng: -8.6106 },
        price: 12,
        description: "Famous for the hearty francesinha sandwich.",
      },
    ],
  },
  {
    id: "seville-es",
    name: "Seville",
    country: "Spain",
    region: "iberia",
    coords: { lat: 37.3891, lng: -5.9845 },
    climate: "warm",
    interests: ["history", "culture", "food"],
    stayPerNight: { backpacker: 27, comfort: 80, luxury: 200 },
    foodPerDay: { backpacker: 20, comfort: 45, luxury: 100 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "seville-alcazar",
        name: "Real Alcázar",
        category: "sight",
        coords: { lat: 37.3831, lng: -5.9903 },
        price: 14,
        description: "Stunning Mudéjar royal palace and gardens.",
      },
      {
        id: "seville-cathedral-giralda",
        name: "Seville Cathedral & Giralda",
        category: "sight",
        coords: { lat: 37.386, lng: -5.993 },
        price: 12,
        description: "World's largest Gothic cathedral with bell tower.",
      },
      {
        id: "seville-plaza-espana",
        name: "Plaza de España",
        category: "sight",
        coords: { lat: 37.3773, lng: -5.9869 },
        price: 0,
        description: "Grand semicircular plaza with tiled alcoves.",
      },
      {
        id: "seville-barrio-santa-cruz",
        name: "Barrio Santa Cruz",
        category: "sight",
        coords: { lat: 37.3866, lng: -5.9903 },
        price: 0,
        description: "Former Jewish quarter of whitewashed alleys.",
      },
      {
        id: "seville-flamenco-show",
        name: "Flamenco Show",
        category: "nightlife",
        coords: { lat: 37.39, lng: -5.995 },
        price: 25,
        description: "Passionate live flamenco in an intimate tablao.",
      },
      {
        id: "seville-triana-market",
        name: "Mercado de Triana",
        category: "food",
        coords: { lat: 37.3833, lng: -6.0031 },
        price: 15,
        description: "Riverside market on ceramic-making grounds.",
      },
      {
        id: "seville-el-rinconcillo",
        name: "El Rinconcillo",
        category: "food",
        coords: { lat: 37.3939, lng: -5.9915 },
        price: 30,
        description: "Seville's oldest tapas bar, dating to 1670.",
      },
    ],
  },
  {
    id: "barcelona-es",
    name: "Barcelona",
    country: "Spain",
    region: "iberia",
    coords: { lat: 41.3851, lng: 2.1734 },
    climate: "warm",
    interests: ["art", "culture", "beach", "nightlife"],
    stayPerNight: { backpacker: 40, comfort: 120, luxury: 300 },
    foodPerDay: { backpacker: 28, comfort: 60, luxury: 140 },
    minDays: 2,
    maxDays: 5,
    pois: [
      {
        id: "barcelona-sagrada-familia",
        name: "Sagrada Família",
        category: "sight",
        coords: { lat: 41.4036, lng: 2.1744 },
        price: 26,
        description: "Gaudí's unfinished basilica masterpiece.",
      },
      {
        id: "barcelona-park-guell",
        name: "Park Güell",
        category: "nature",
        coords: { lat: 41.4145, lng: 2.1527 },
        price: 10,
        description: "Whimsical mosaic park overlooking the city.",
      },
      {
        id: "barcelona-gothic-quarter",
        name: "Gothic Quarter",
        category: "sight",
        coords: { lat: 41.3833, lng: 2.177 },
        price: 0,
        description: "Medieval maze of squares and cathedrals.",
      },
      {
        id: "barcelona-la-boqueria",
        name: "La Boqueria Market",
        category: "food",
        coords: { lat: 41.3818, lng: 2.1716 },
        price: 15,
        description: "Bustling market off Las Ramblas.",
      },
      {
        id: "barcelona-barceloneta-beach",
        name: "Barceloneta Beach",
        category: "nature",
        coords: { lat: 41.3784, lng: 2.1925 },
        price: 0,
        description: "City's popular sandy beachfront.",
      },
      {
        id: "barcelona-picasso-museum",
        name: "Picasso Museum",
        category: "museum",
        coords: { lat: 41.3851, lng: 2.1809 },
        price: 14,
        description: "Extensive collection of Picasso's early works.",
      },
      {
        id: "barcelona-razzmatazz",
        name: "Razzmatazz",
        category: "nightlife",
        coords: { lat: 41.3986, lng: 2.1925 },
        price: 20,
        description: "Iconic multi-room nightclub near Poblenou.",
      },
    ],
  },
  {
    id: "madrid-es",
    name: "Madrid",
    country: "Spain",
    region: "iberia",
    coords: { lat: 40.4168, lng: -3.7038 },
    climate: "temperate",
    interests: ["culture", "art", "food", "nightlife"],
    stayPerNight: { backpacker: 38, comfort: 115, luxury: 290 },
    foodPerDay: { backpacker: 26, comfort: 58, luxury: 135 },
    minDays: 2,
    maxDays: 4,
    pois: [
      {
        id: "madrid-prado-museum",
        name: "Prado Museum",
        category: "museum",
        coords: { lat: 40.4138, lng: -3.6921 },
        price: 15,
        description: "World-class collection of European masters.",
      },
      {
        id: "madrid-retiro-park",
        name: "Retiro Park",
        category: "nature",
        coords: { lat: 40.4153, lng: -3.6844 },
        price: 0,
        description: "Grand park with a boating lake and glass palace.",
      },
      {
        id: "madrid-plaza-mayor",
        name: "Plaza Mayor",
        category: "sight",
        coords: { lat: 40.4155, lng: -3.7074 },
        price: 0,
        description: "Historic arcaded square in the city center.",
      },
      {
        id: "madrid-royal-palace",
        name: "Royal Palace of Madrid",
        category: "sight",
        coords: { lat: 40.418, lng: -3.7144 },
        price: 13,
        description: "Official residence with opulent state rooms.",
      },
      {
        id: "madrid-mercado-san-miguel",
        name: "Mercado de San Miguel",
        category: "food",
        coords: { lat: 40.4155, lng: -3.7092 },
        price: 20,
        description: "Glass-walled gourmet tapas market.",
      },
      {
        id: "madrid-reina-sofia",
        name: "Reina Sofía Museum",
        category: "museum",
        coords: { lat: 40.4084, lng: -3.6947 },
        price: 12,
        description: "Home to Picasso's Guernica and modern art.",
      },
      {
        id: "madrid-teatro-kapital",
        name: "Teatro Kapital",
        category: "nightlife",
        coords: { lat: 40.4088, lng: -3.6944 },
        price: 25,
        description: "Seven-floor nightclub, a Madrid institution.",
      },
    ],
  },
];
