import { City } from "../types";

export const ITALY: City[] = [
  {
    id: "rome-it",
    name: "Rome",
    country: "Italy",
    region: "italy",
    coords: { lat: 41.9028, lng: 12.4964 },
    climate: "warm",
    interests: ["history", "culture", "art", "food"],
    stayPerNight: { backpacker: 35, comfort: 110, luxury: 280 },
    foodPerDay: { backpacker: 25, comfort: 55, luxury: 130 },
    minDays: 3,
    maxDays: 5,
    pois: [
      {
        id: "rome-colosseum",
        name: "Colosseum",
        category: "sight",
        coords: { lat: 41.8902, lng: 12.4922 },
        price: 18,
        description: "Ancient amphitheater and symbol of Rome.",
      },
      {
        id: "rome-roman-forum",
        name: "Roman Forum",
        category: "sight",
        coords: { lat: 41.8925, lng: 12.4853 },
        price: 16,
        description: "Ruins of the political heart of ancient Rome.",
      },
      {
        id: "rome-vatican-museums",
        name: "Vatican Museums",
        category: "museum",
        coords: { lat: 41.9065, lng: 12.4536 },
        price: 21,
        description: "Vast collection culminating in the Sistine Chapel.",
      },
      {
        id: "rome-trevi-fountain",
        name: "Trevi Fountain",
        category: "sight",
        coords: { lat: 41.9009, lng: 12.4833 },
        price: 0,
        description: "Baroque fountain famous for coin tossing.",
      },
      {
        id: "rome-pantheon",
        name: "Pantheon",
        category: "sight",
        coords: { lat: 41.8986, lng: 12.4769 },
        price: 0,
        description: "Best-preserved Roman temple with a vast dome.",
      },
      {
        id: "rome-trastevere",
        name: "Trastevere",
        category: "sight",
        coords: { lat: 41.8896, lng: 12.47 },
        price: 0,
        description: "Cobbled riverside district full of trattorias.",
      },
      {
        id: "rome-da-enzo",
        name: "Da Enzo al 29",
        category: "food",
        coords: { lat: 41.8889, lng: 12.478 },
        price: 35,
        description: "Beloved trattoria for classic Roman pasta.",
      },
      {
        id: "rome-testaccio-nightlife",
        name: "Testaccio Nightlife",
        category: "nightlife",
        coords: { lat: 41.8757, lng: 12.475 },
        price: 20,
        description: "Former slaughterhouse district turned club scene.",
      },
    ],
  },
  {
    id: "florence-it",
    name: "Florence",
    country: "Italy",
    region: "italy",
    coords: { lat: 43.7696, lng: 11.2558 },
    climate: "temperate",
    interests: ["art", "culture", "history"],
    stayPerNight: { backpacker: 33, comfort: 100, luxury: 260 },
    foodPerDay: { backpacker: 24, comfort: 52, luxury: 120 },
    minDays: 2,
    maxDays: 4,
    pois: [
      {
        id: "florence-uffizi",
        name: "Uffizi Gallery",
        category: "museum",
        coords: { lat: 43.7678, lng: 11.2553 },
        price: 20,
        description: "Renaissance masterpieces by Botticelli and da Vinci.",
      },
      {
        id: "florence-duomo",
        name: "Florence Cathedral (Duomo)",
        category: "sight",
        coords: { lat: 43.7731, lng: 11.256 },
        price: 18,
        description: "Iconic dome by Brunelleschi over the old city.",
      },
      {
        id: "florence-ponte-vecchio",
        name: "Ponte Vecchio",
        category: "sight",
        coords: { lat: 43.768, lng: 11.2531 },
        price: 0,
        description: "Medieval bridge lined with jewelry shops.",
      },
      {
        id: "florence-accademia",
        name: "Accademia Gallery",
        category: "museum",
        coords: { lat: 43.7767, lng: 11.2588 },
        price: 16,
        description: "Home of Michelangelo's David.",
      },
      {
        id: "florence-boboli-gardens",
        name: "Boboli Gardens",
        category: "nature",
        coords: { lat: 43.7644, lng: 11.2497 },
        price: 10,
        description: "Grand Renaissance gardens behind Pitti Palace.",
      },
      {
        id: "florence-mercato-centrale",
        name: "Mercato Centrale",
        category: "food",
        coords: { lat: 43.7765, lng: 11.2536 },
        price: 20,
        description: "Two-story food market and dining hall.",
      },
      {
        id: "florence-oltrarno",
        name: "Oltrarno District",
        category: "sight",
        coords: { lat: 43.7654, lng: 11.247 },
        price: 0,
        description: "Artisan workshops across the Arno river.",
      },
    ],
  },
  {
    id: "venice-it",
    name: "Venice",
    country: "Italy",
    region: "italy",
    coords: { lat: 45.4408, lng: 12.3155 },
    climate: "temperate",
    interests: ["culture", "art", "history"],
    stayPerNight: { backpacker: 45, comfort: 140, luxury: 350 },
    foodPerDay: { backpacker: 30, comfort: 65, luxury: 150 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "venice-st-marks-basilica",
        name: "St. Mark's Basilica",
        category: "sight",
        coords: { lat: 45.4343, lng: 12.3388 },
        price: 3,
        description: "Byzantine-style cathedral of glittering mosaics.",
      },
      {
        id: "venice-doges-palace",
        name: "Doge's Palace",
        category: "museum",
        coords: { lat: 45.4335, lng: 12.3401 },
        price: 25,
        description: "Gothic palace and former seat of Venetian power.",
      },
      {
        id: "venice-rialto-bridge",
        name: "Rialto Bridge",
        category: "sight",
        coords: { lat: 45.438, lng: 12.3358 },
        price: 0,
        description: "Iconic stone bridge over the Grand Canal.",
      },
      {
        id: "venice-grand-canal-gondola",
        name: "Grand Canal Gondola Ride",
        category: "activity",
        coords: { lat: 45.437, lng: 12.335 },
        price: 80,
        description: "Classic gondola glide past palazzo façades.",
      },
      {
        id: "venice-murano-island",
        name: "Murano Island",
        category: "activity",
        coords: { lat: 45.459, lng: 12.3505 },
        price: 0,
        description: "Glass-blowing island a short ferry away.",
      },
      {
        id: "venice-burano-island",
        name: "Burano Island",
        category: "sight",
        coords: { lat: 45.4854, lng: 12.416 },
        price: 0,
        description: "Fishing island famous for colorful houses.",
      },
      {
        id: "venice-osteria-alle-testiere",
        name: "Osteria Alle Testiere",
        category: "food",
        coords: { lat: 45.4363, lng: 12.3413 },
        price: 55,
        description: "Tiny seafood osteria beloved by locals.",
      },
    ],
  },
  {
    id: "naples-it",
    name: "Naples",
    country: "Italy",
    region: "italy",
    coords: { lat: 40.8518, lng: 14.2681 },
    climate: "warm",
    interests: ["food", "history", "culture", "adventure"],
    stayPerNight: { backpacker: 28, comfort: 85, luxury: 210 },
    foodPerDay: { backpacker: 20, comfort: 45, luxury: 100 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "naples-pompeii",
        name: "Pompeii Ruins",
        category: "sight",
        coords: { lat: 40.7461, lng: 14.4989 },
        price: 18,
        description: "Ancient city frozen by Vesuvius's eruption.",
      },
      {
        id: "naples-spaccanapoli",
        name: "Spaccanapoli",
        category: "sight",
        coords: { lat: 40.8494, lng: 14.2569 },
        price: 0,
        description: "Narrow historic street splitting the old center.",
      },
      {
        id: "naples-castel-dellovo",
        name: "Castel dell'Ovo",
        category: "sight",
        coords: { lat: 40.8288, lng: 14.2469 },
        price: 0,
        description: "Seafront castle on a former island.",
      },
      {
        id: "naples-archaeological-museum",
        name: "National Archaeological Museum",
        category: "museum",
        coords: { lat: 40.8532, lng: 14.2504 },
        price: 15,
        description: "Treasures recovered from Pompeii and Herculaneum.",
      },
      {
        id: "naples-pizzeria-da-michele",
        name: "L'Antica Pizzeria da Michele",
        category: "food",
        coords: { lat: 40.8508, lng: 14.2645 },
        price: 8,
        description: "Legendary pizzeria serving since 1870.",
      },
      {
        id: "naples-vesuvius-hike",
        name: "Mount Vesuvius Hike",
        category: "nature",
        coords: { lat: 40.8214, lng: 14.4262 },
        price: 12,
        description: "Crater-rim hike overlooking the Bay of Naples.",
      },
      {
        id: "naples-underground",
        name: "Napoli Sotterranea",
        category: "activity",
        coords: { lat: 40.8508, lng: 14.2557 },
        price: 12,
        description: "Guided tour of tunnels beneath the old city.",
      },
    ],
  },
  {
    id: "milan-it",
    name: "Milan",
    country: "Italy",
    region: "italy",
    coords: { lat: 45.4642, lng: 9.19 },
    climate: "temperate",
    interests: ["culture", "art", "food", "nightlife"],
    stayPerNight: { backpacker: 40, comfort: 125, luxury: 300 },
    foodPerDay: { backpacker: 28, comfort: 60, luxury: 140 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "milan-duomo",
        name: "Milan Cathedral (Duomo)",
        category: "sight",
        coords: { lat: 45.4642, lng: 9.19 },
        price: 5,
        description: "Spired Gothic cathedral with rooftop terraces.",
      },
      {
        id: "milan-last-supper",
        name: "The Last Supper",
        category: "museum",
        coords: { lat: 45.4661, lng: 9.1704 },
        price: 15,
        description: "Da Vinci's mural at Santa Maria delle Grazie.",
      },
      {
        id: "milan-galleria-vittorio",
        name: "Galleria Vittorio Emanuele II",
        category: "sight",
        coords: { lat: 45.4655, lng: 9.1896 },
        price: 0,
        description: "Grand 19th-century glass-domed shopping arcade.",
      },
      {
        id: "milan-brera",
        name: "Pinacoteca di Brera",
        category: "museum",
        coords: { lat: 45.4719, lng: 9.188 },
        price: 15,
        description: "Fine art museum in the artsy Brera district.",
      },
      {
        id: "milan-sforza-castle",
        name: "Sforza Castle",
        category: "sight",
        coords: { lat: 45.4703, lng: 9.1794 },
        price: 10,
        description: "Renaissance fortress housing several museums.",
      },
      {
        id: "milan-navigli",
        name: "Navigli District",
        category: "nightlife",
        coords: { lat: 45.4515, lng: 9.1739 },
        price: 15,
        description: "Canal-side bars famous for aperitivo hour.",
      },
      {
        id: "milan-luini-panzerotti",
        name: "Luini Panzerotti",
        category: "food",
        coords: { lat: 45.4646, lng: 9.1885 },
        price: 6,
        description: "Cult favorite for fried panzerotti snacks.",
      },
    ],
  },
];
