import { City } from "../types";

export const NORDICS: City[] = [
  {
    id: "copenhagen-dk",
    name: "Copenhagen",
    country: "Denmark",
    region: "nordics",
    coords: { lat: 55.6761, lng: 12.5683 },
    climate: "cold",
    interests: ["culture", "food", "nightlife"],
    stayPerNight: { backpacker: 45, comfort: 160, luxury: 380 },
    foodPerDay: { backpacker: 30, comfort: 65, luxury: 150 },
    minDays: 2,
    maxDays: 4,
    pois: [
      {
        id: "copenhagen-dk-nyhavn",
        name: "Nyhavn",
        category: "sight",
        coords: { lat: 55.6799, lng: 12.591 },
        price: 0,
        description: "Colorful 17th-century harbor lined with cafés.",
      },
      {
        id: "copenhagen-dk-tivoli-gardens",
        name: "Tivoli Gardens",
        category: "activity",
        coords: { lat: 55.6736, lng: 12.5681 },
        price: 28,
        description: "Historic amusement park in the heart of the city.",
      },
      {
        id: "copenhagen-dk-little-mermaid",
        name: "The Little Mermaid",
        category: "sight",
        coords: { lat: 55.6929, lng: 12.5993 },
        price: 0,
        description: "Iconic bronze statue overlooking the harbor.",
      },
      {
        id: "copenhagen-dk-national-museum",
        name: "National Museum of Denmark",
        category: "museum",
        coords: { lat: 55.675, lng: 12.573 },
        price: 0,
        description: "Free museum covering Danish history and culture.",
      },
      {
        id: "copenhagen-dk-torvehallerne",
        name: "Torvehallerne Food Market",
        category: "food",
        coords: { lat: 55.6836, lng: 12.568 },
        price: 20,
        description: "Gourmet food market with fresh Nordic produce.",
      },
      {
        id: "copenhagen-dk-meatpacking-district",
        name: "Meatpacking District",
        category: "nightlife",
        coords: { lat: 55.6656, lng: 12.5638 },
        price: 40,
        description: "Trendy former industrial area with bars and clubs.",
      },
    ],
  },
  {
    id: "stockholm-se",
    name: "Stockholm",
    country: "Sweden",
    region: "nordics",
    coords: { lat: 59.3293, lng: 18.0686 },
    climate: "cold",
    interests: ["culture", "history", "nature"],
    stayPerNight: { backpacker: 42, comfort: 150, luxury: 360 },
    foodPerDay: { backpacker: 28, comfort: 60, luxury: 140 },
    minDays: 2,
    maxDays: 4,
    pois: [
      {
        id: "stockholm-se-gamla-stan",
        name: "Gamla Stan",
        category: "sight",
        coords: { lat: 59.3251, lng: 18.0711 },
        price: 0,
        description: "Medieval old town with narrow cobbled lanes.",
      },
      {
        id: "stockholm-se-vasa-museum",
        name: "Vasa Museum",
        category: "museum",
        coords: { lat: 59.328, lng: 18.0913 },
        price: 17,
        description: "Preserved 17th-century warship, remarkably intact.",
      },
      {
        id: "stockholm-se-royal-palace",
        name: "Royal Palace",
        category: "sight",
        coords: { lat: 59.3269, lng: 18.0714 },
        price: 17,
        description: "Official residence of the Swedish monarch.",
      },
      {
        id: "stockholm-se-skansen",
        name: "Skansen",
        category: "activity",
        coords: { lat: 59.3238, lng: 18.1027 },
        price: 22,
        description: "Open-air museum showcasing Swedish life and wildlife.",
      },
      {
        id: "stockholm-se-djurgarden",
        name: "Djurgården",
        category: "nature",
        coords: { lat: 59.3251, lng: 18.1006 },
        price: 0,
        description: "Green island park popular for walking and cycling.",
      },
      {
        id: "stockholm-se-sodermalm-nightlife",
        name: "Södermalm Nightlife",
        category: "nightlife",
        coords: { lat: 59.3157, lng: 18.071 },
        price: 35,
        description: "Hip neighborhood with bars and live music venues.",
      },
    ],
  },
  {
    id: "oslo-no",
    name: "Oslo",
    country: "Norway",
    region: "nordics",
    coords: { lat: 59.9139, lng: 10.7522 },
    climate: "cold",
    interests: ["nature", "adventure", "culture"],
    stayPerNight: { backpacker: 45, comfort: 155, luxury: 370 },
    foodPerDay: { backpacker: 30, comfort: 65, luxury: 145 },
    minDays: 1,
    maxDays: 3,
    pois: [
      {
        id: "oslo-no-vigeland-park",
        name: "Vigeland Park",
        category: "nature",
        coords: { lat: 59.927, lng: 10.7005 },
        price: 0,
        description: "Sprawling sculpture park by Gustav Vigeland.",
      },
      {
        id: "oslo-no-viking-ship-museum",
        name: "Viking Ship Museum",
        category: "museum",
        coords: { lat: 59.9047, lng: 10.6845 },
        price: 15,
        description: "Well-preserved Viking-era ships and artifacts.",
      },
      {
        id: "oslo-no-opera-house",
        name: "Oslo Opera House",
        category: "sight",
        coords: { lat: 59.9075, lng: 10.753 },
        price: 0,
        description: "Striking waterfront building you can walk on top of.",
      },
      {
        id: "oslo-no-holmenkollen",
        name: "Holmenkollen Ski Jump",
        category: "activity",
        coords: { lat: 60.0157, lng: 10.6683 },
        price: 16,
        description: "Historic ski jump with museum and city views.",
      },
      {
        id: "oslo-no-fjord-kayaking",
        name: "Oslofjord Kayaking",
        category: "activity",
        coords: { lat: 59.902, lng: 10.73 },
        price: 55,
        description: "Guided kayak tour of the scenic Oslofjord.",
      },
      {
        id: "oslo-no-mathallen",
        name: "Mathallen Food Hall",
        category: "food",
        coords: { lat: 59.9226, lng: 10.753 },
        price: 25,
        description: "Indoor food hall with local and international eats.",
      },
    ],
  },
];
